// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PropertyViewing.Infrastructure.Persistence;

#nullable disable

namespace PropertyViewing.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260913101432_AddPropertyTimeZoneAndFixTimestampType")]
    partial class AddPropertyTimeZoneAndFixTimestampType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PropertyViewing.Domain.Entities.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Europe/London");

                    b.HasKey("Id");

                    b.ToTable("properties", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "1 Main Street",
                            TimeZoneId = "Europe/London"
                        },
                        new
                        {
                            Id = 2,
                            Address = "2 High Street",
                            TimeZoneId = "America/New_York"
                        },
                        new
                        {
                            Id = 3,
                            Address = "3 Park Avenue",
                            TimeZoneId = "Asia/Ho_Chi_Minh"
                        });
                });

            modelBuilder.Entity("PropertyViewing.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "user1@example.test",
                            Name = "User 1"
                        },
                        new
                        {
                            Id = 2,
                            Email = "user2@example.test",
                            Name = "User 2"
                        },
                        new
                        {
                            Id = 3,
                            Email = "user3@example.test",
                            Name = "User 3"
                        });
                });

            modelBuilder.Entity("PropertyViewing.Domain.Entities.Viewing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PropertyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StartTime");

                    b.HasIndex("UserId");

                    b.HasIndex("PropertyId", "StartTime")
                        .IsUnique();

                    b.ToTable("viewings", (string)null);
                });

            modelBuilder.Entity("PropertyViewing.Domain.Entities.Viewing", b =>
                {
                    b.HasOne("PropertyViewing.Domain.Entities.Property", "Property")
                        .WithMany("Viewings")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PropertyViewing.Domain.Entities.User", "User")
                        .WithMany("Viewings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Property");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PropertyViewing.Domain.Entities.Property", b =>
                {
                    b.Navigation("Viewings");
                });

            modelBuilder.Entity("PropertyViewing.Domain.Entities.User", b =>
                {
                    b.Navigation("Viewings");
                });
#pragma warning restore 612, 618
        }
    }
}
